### PR TITLE
Update ego_dp_rea_results.sql

### PR DESCRIPTION
**Pull request by IlkaCu**
Hotfix to fill empty cells in rea_geom_new.

### CODE REVIEW

**Comment by IlkaCu** [comment]
@wolfbunke Do you know which SRID the columns rea_geom_new and geom have at the end of the rea scripts. I just noticed that we might need an additional ST_Transform statement here.

**Comment by wolfbunke** [comment]
At the moment the geom is unchanged:
```
 rea_geom_line geometry(LineString,3035),
 rea_geom_new geometry(Point,3035),
```

**Comment by wolfbunke** [comment]
But I am not sure, if we change it to SRID 4326 that Ding0 and eTraGo get's problems with this change.

**Comment by wolfbunke** [comment]
I changed it to 3035. It shouldn't affect Ding0 or eDisGo.

**Pull request merged**
