### PR TITLE
Add and integrate NEP-data and extension-tables

### PR DESCRIPTION
**Pull request by ClaraBuettner**
I added a sql-script creating extension_ tables and insert extension lines, trafos, buses from the NEP. An input-file ist needed in the documentation folder. The scripts are included at the end of the dataprocessing. 

In 'ego_pp_nep2035_grid_variations' I couldn't find a possibility to automatically find the path to the csv-file in the documentation folder. So that won't work right now. Is there a way to do that?

### CODE REVIEW

**Comment by IlkaCu** [comment]
Could we import the csv as a model_draft table and use this as an input for the sql-snippet instead?

**Comment by ClaraBuettner** [comment]
Yes, it's much better to import the model_draft.scn_nep2035_b2_line only once and rename it. I just changed the owner to oeuser.

**Comment by ClaraBuettner** [comment]
Ok, so I update the description directly in the release branch?

**Comment by IlkaCu** [comment]
Yes, please.

**Pull request merged**
