### PR TITLE
Assign storages to neighbouring countries

### PR DESCRIPTION
**Pull request by s3pp**
Implement #129

### CODE REVIEW

**Comment by lukasol** [comment]
I will update the parameters before the merge.

**Comment by ulfmueller** [comment]
@lukasol do you just want to review the request then and change the parameters as you wish and then do the merge?

**Comment by lukasol** [comment]
Yes, can do so.

**Comment by lukasol** [comment]
Obviously, the capacities for the eGo 100 are not in the renpassgis schema yet. @wolfbunke do you know why?

**Comment by wolfbunke** [comment]
Hi @lukasol, it just get lost by the daily workflow.  I will start the renpasGIS eGo 100 scenario calculation now and insert it via [scenario_import ](https://github.com/openego/data_processing/tree/dev/preprocessing/python_scripts/renpass_gis/scenario_import)in the oedb.

**Comment by wolfbunke** [comment]
The results of the renpassGIS eGo 100 scenario can be found in the database. Scenario id =**39,** scenario name =**eGo 100**.

**Comment by ulfmueller** [comment]
Thx @wolfbunke ! I added a tiny additional line. I think now it is all yours @lukasol for your adjustments and the merge! :+1:

**Comment by lukasol** [comment]
Another question:
In calc_renpass_gis.renpass_gis_storage there are the two columns "nominal_value" and "nominal_capacity". Currently the p_nom in the powerflow data is taken from "nominal_value". The data in the two columns is different: The "nominal_capacity" is bigger by the factor 10. Example:
nominal_value: 1900
nominal_capacity: 19000

Are you certain that nominal_value is the right choice? Or in other words: where is the difference?

**Comment by lukasol** [comment]
> Are you certain that nominal_value is the right choice? Or in other words: where is the difference?

Ok, I guess it's the capacity in terms of energy [GWh]...

**Comment by lukasol** [comment]
are we sure to merge into release/v0.3 and not into dev?

**Comment by wolfbunke** [comment]
yes. You found the answer quicker as I could reply.

**Comment by ulfmueller** [comment]
> are we sure to merge into release/v0.3 and not into dev?
yes. @IlkaCu said so. That way she will include it in the current version... (good question though! ;) it is rather an exception to the rule...)

**Pull request merged**
