### PR TITLE
add script of pp mviews for schema supply

### PR DESCRIPTION
**Pull request by wolfbunke**
Add power plant MViews for schema supply of each eGo scenario

### CODE REVIEW

**Comment by nesnoj** [comment]
I added myself to reviewers coz I wanna check some stuff in the result data..

**Comment by nesnoj** [comment]
Please add permissions to oeuser for MVIEWs..

**Comment by wolfbunke** [comment]
oeuser is set

**Comment by wolfbunke** [comment]
I thought the preversion is maybe good to see witch predataprocessing we used? But I am changing my mind very time because it has pro and cons knowing from which pre run those data are.

**Comment by IlkaCu** [comment]
I guess nesnoj meant to remove the 'pre' suffix from _version = 'v0.3.0pre1'_

**Comment by wolfbunke** [comment]
oh yes

**Pull request merged**
