### PR TITLE
Fix #272

### LINKED ISSUE #272: Include w_id in Generators table in supply
Versioned data and model_draft data of v0.4.0 is not identical!

Versioned in supply misses the `w_id`. This affects
- supply.ego_dp_res_powerplant
- supply.ego_dp_res_powerplant_sq_mview
- supply.ego_dp_res_powerplant_nep2035_mview
- supply.ego_dp_res_powerplant_ego100_mview

### PR DESCRIPTION
**Pull request by wolfbunke**
I found the bug in the version code and fixed it.

### CODE REVIEW

**Comment by IlkaCu** [comment]
Furthermore the table supply.ego_dp_res_powerplant itself is not updated yet. Please add the column w_id there as well and adjust the corresponding setup script which should be included somewhere in the preprocessing.

**Comment by IlkaCu** [comment]
Even better you merge it into the release/v0.4.0 branch. As I am planning to start a new clean run for version 0.4.1 during the weekend.

**Comment by gplssm** [comment]
As @wolfbunke might be unavailable, I'll try to
1. include w_id n script for supply.ego_dp_res_powerplant
2. include w_id in preprocessing for both tables (model_draft and supply)
2. merge it to release/v0.4.0 branch

When is the deadline?

**Comment by gplssm** [comment]
> merge it to release/v0.4.0 branch
@IlkaCu did you create a release/v0.4.1 branch or do you still you the v0.4.0 branch?

**Comment by gplssm** [comment]
> 1. include w_id n script for supply.ego_dp_res_powerplant

was already done by 48c5adbbea4fa7d8f443e6e1e8153367fec9a0f4 as far as I understand it

> 2. include w_id in preprocessing for both tables (model_draft and supply)

was already included for the model_draft table. I added it just for supply

**Comment by gplssm** [comment]
This PR needs to be closed before a new PR with different target can be created from this branch

**Comment by IlkaCu** [comment]
> @IlkaCu did you create a release/v0.4.1 branch or do you still you the v0.4.0 branch?

In the meantime I created release/v0.4.1 which I use for this 'minor' release.

**Pull request closed without merging**
