### PR TITLE
change SRID

### PR DESCRIPTION
**Pull request by IlkaCu**
This should fix the problem described in #243

### CODE REVIEW

**Comment by nesnoj** [comment]
Why would you set a different SRID on single cells? Isn't it better to transform it to 3035?

**Comment by IlkaCu** [comment]
The column 'geom' has the SRID 4326. The problem described in #243 occurred because single cells where transformed to 3035 - therefore I changed it back to 4326.

**Comment by nesnoj** [comment]
I don't get it. The [CREATE-statement says](https://github.com/openego/data_processing/blob/109cb62179f96738144b6afbffd4340821c1f892/preprocessing/sql_snippets/ego_dp_preprocessing_res_powerplant.sql#L42) it's 3035.

If I'm not mislead, the correct one is
```
ST_Transform(ST_SetSRID(ST_MakePoint(6.48, 53.69), 4326), 3035)
```
because you say this point is WGS84, then you transform to ETRS (which is the SRID of the column `geom`). Not sure if this (extra?) transformation is necessary?

**Comment by wolfbunke** [comment]
But the table is using SRID 3035  https://github.com/openego/data_processing/blob/dev/preprocessing/sql_snippets/ego_dp_preprocessing_res_powerplant.sql#L42 . As fare I remember we changed it to have the rea scripts faster and change the geom later back to SRID 4326 .   

I think @nesnoj  is right the problem is mixing  WGS lon/lat (4326) and SRID  3035.

**Comment by IlkaCu** [comment]
I didn't notice the SRID in the Create-Statement - in the database it is 4326. Confusing! 
But as you can see I changed the code according to @nesnoj's remarks.

**Pull request merged**
