### PR TITLE
Fixes #111

### LINKED ISSUE #111: Update all metadata to version 1.3
metadata must follow new version 1.3.
@Ludee: 

- [x] Check all eGoDP tables (versioning)
Check all Input tables (OSM, borders, zensus)
- [x]  OSM
- [x] borders
- [x] zensus
- [x] gva (economic.destatis_gva_per_district)
- [x] demand federalstate (demand.ego_demand_federalstate)
- [x] wpa (supply.vernetzen_wind_potential_area)
- [x] supply.* @wolfbunke 
- [ ] forwind (supply.forwind_oeko_renewable_capacity_per_federalstate)
- [x] boundaries.gn250_b and boundaries.gn250_p

@MGlauer: 
- [x] Adjust OEP to display all fields from new version

### PR DESCRIPTION
**Pull request by KilianZimmerer**
Update of the 'ego_dp_structure_versioning.sql' by metadata v1.3

### CODE REVIEW

**Comment by Ludee** [comment]
This fixes the first checkbox from #111 `Check all eGoDP tables (versioning)`.
Metadata strings are a little bit too long.
Thanks to @KilianZimmerer we have a metadata version conversion script.

**Comment by Ludee** [comment]
There are 4 conflicts now:
- [ ] grid.ego_dp_ehv_substation
- [ ] grid.ego_dp_hvmv_substation
- [ ] grid.ego_pf_hv_line
- [ ] grid.ego_pf_hv_transformer
Did you update the metadata? @IlkaCu @lukasol 
Can you approve and resolve so we can merge this PR

**Comment by IlkaCu** [comment]
I didn't change anything here. It seems that @lukasol adjusted the copyright.

**Comment by Ludee** [comment]
Thanks for the info @IlkaCu. That should be easy to resolve. I will merge this PR now.

**Pull request merged**
