### PR TITLE
Add BPMN for scenario_log part

### LINKED ISSUE #355: there is no DP preprocessing BPMN documentation about scenario_log

### PR DESCRIPTION
**Pull request by gplssm**
fix #355

### CODE REVIEW

**Comment by IlkaCu** [comment]
The BPMN shows the script ego_pp_scenario.sql and the resulting table model_draft.ego_scenario twice. Is this intended?

**Comment by gplssm** [comment]
My fault! Classic copy&paste one. Is now fixed.

**Comment by IlkaCu** [comment]
I still see the doupling... 🤔

**Comment by gplssm** [comment]
Hmm, I really fixed it and included the changes in 2794f32 :crossed_fingers: 

What I see is the following

grafik

The changes are big. So, you have look carefully.

**Comment by IlkaCu** [comment]
My mistake! Sorry.

**Review by IlkaCu — APPROVED** [review]

**Pull request merged**
