### PR TITLE
Fix/#76

### PR DESCRIPTION
**Pull request by Ludee**
Translated the file _python_scripts\ego_dp_loadarea_peakload.py_ that took about 10 hours to execute to an SQL file using an simplified method. New script needs about 5 min to execute.

### CODE REVIEW

**Comment by Ludee** [comment]
There is a minor difference in the results (only checked residential) using this:

```SQL
SELECT la.subst_id,
                la.id AS a_id,
                la.sector_peakload_retail AS a_sector_peakload_retail,
                v_la.id AS a_id,
                v_la.sector_peakload_retail AS a_sector_peakload_retail,
                la.sector_peakload_retail - v_la.sector_peakload_retail AS dif
FROM   model_draft.ego_demand_loadarea AS la
                JOIN demand.ego_dp_loadarea AS v_la ON (la.id = v_la.id)
WHERE v_la.version = 'v0.2.10' AND
                la.sector_peakload_retail <> v_la.sector_peakload_retail
ORDER BY la.id
LIMIT 100;
```

**Comment by gplssm** [comment]
If we take a look on the deviation in each sector
peakload_deviation_in_sectors
either zero (in case of no sectoral load) or a sector-specific constant deviation can be observed.

Sector | Relative deviation
-------- | ----------------------
rel_diff_retail | 0.013732
rel_diff_residential | 0.015829
rel_diff_industrial | -0.000744
rel_diff_agricultural | 0.032794

**Comment by Ludee** [comment]
How to handle this difference? Should we just merge the PR?

**Comment by gplssm** [comment]
I took a look at the ratio of peak load/consumption for both versions of peak load calculation in LAs.

The version in demand.ego_dp_loadarea analyzed by 

```
SELECT id,
       sector_peakload_retail / sector_consumption_retail
  FROM demand.ego_dp_loadarea
  WHERE sector_consumption_retail > 0
```
shows a bunch of ratios with no pattern.

On the other hand, analyzing the data of peak loads generated with the new SQL-script perfectly reflect the defined ratio of scenario.ego_slp_parameters. Analysis performed by

```
SELECT id,
       sector_peakload_retail / sector_consumption_retail
  FROM model_draft.ego_demand_loadarea
  WHERE sector_consumption_retail > 0
```

Thus, I would say let's take the new version of data! Any objections?

**Pull request merged**
