### PR TITLE
Draft BPMN

### LINKED ISSUE #335: there is no DP preprocessing BPMN documentation about supply tables
Provide BPMN decribing importand preprocessing of power plant and feedin data, more precisely these tables

- model_draft.ego_dp_supply_conv_powerplant
- model_draft.ego_dp_supply_res_powerplant
- model_draft.ego_renewable_feedin

### PR DESCRIPTION
**Pull request by gplssm**
fix #335

### CODE REVIEW

**Comment by IlkaCu** [comment]
@gplssm: Could you have a look on the changes I added? As you intialized this PR I can't set you as a reviewer.

**Comment by gplssm** [comment]
Sure!

I cannot comment on the details of this, as I don't know more than you  here.
For me, in general, it looks meaningfull: relevant tables and scripts are connected. Missing datasets and script are highlighted in red. It's quite intuitive!

I was just wondering why there are some missing arrows?

ego_pp_bpmn_section_supply

**Comment by IlkaCu** [comment]
Obviously something went wrong here. This is not the final version I intended to merge. I will check that out.

**Comment by IlkaCu** [comment]
The image you posted shows the simple_feedin BPMN, but the PR aims to update ego_dp-pre_bpmn_section_supply.graphml for the supply section.

**Comment by IlkaCu** [comment]
I removed the redundant and incorrect file ego_pp_bpmn_section_supply.graphml which caused the confusion above.

**Pull request merged**
