### PR TITLE
added new technologies for storages in neighbouring countries in scn …

### PR DESCRIPTION
**Pull request by lukasoldi**
please see #275 

Should work fine now, but I am not certain if this will comply with the changes by @wolfbunke in #283 since in my tests I was having trouble finding storages in LU and AT. @wolfbunke can you check?

### CODE REVIEW

**Comment by lukasoldi** [comment]
I just found an issue that I couldn't resolve, but must be easy for some of you: the storage_id is not unique, since it just uses the row_number of the sql query plus 200000. since we have several queries, some are doubled. Any nice ideas on how to resolve that?

**Comment by IlkaCu** [comment]
> I just found an issue that I couldn't resolve, but must be easy for some of you: the storage_id is not unique, since it just uses the row_number of the sql query plus 200000. since we have several queries, some are doubled. Any nice ideas on how to resolve that?

We could introduce a sequence starting with max(storage_id)+200000. I'll try to introduce it in the code.

**Comment by lukasoldi** [comment]
Thanks for the updates @IlkaCu 
@ulfmueller and @wolfbunke could you re-check or add your reviews?

**Comment by wolfbunke** [comment]
By changing the storage_id what happens with this code part?
https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_storage.sql#L346-L348

**Comment by lukasoldi** [comment]
> By changing the storage_id what happens with this code part?
https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_storage.sql#L346-L348

Good point. @IlkaCu could we just add a '+200000' to the sequences?

**Comment by lukasoldi** [comment]
I think it would be nice to somehow test this or do you think that the dp run is enough testing? If you're all ok with the latter I could merge.

**Comment by IlkaCu** [comment]
> Good point. @IlkaCu could we just add a '+200000' to the sequences?

It's already there, but included in the sequence itself: https://github.com/openego/data_processing/blob/feature/fix_%23275/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_storage.sql#L359

**Comment by IlkaCu** [comment]
> By changing the storage_id what happens with this code part?
https://github.com/openego/data_processing/blob/master/dataprocessing/sql_snippets/ego_dp_powerflow_assignment_storage.sql#L346-L348

This part of the code may cause a problem when the storage_id of storages within Germany exceeds 20000. Those ones would be deleted then. From my point of view this part of the code can be removed as the whole table is dropped in the beginning of the powerflow-part.

**Comment by lukasoldi** [comment]
> This part of the code may cause a problem when the storage_id of storages within Germany exceeds 20000. Those ones would be deleted then. From my point of view this part of the code can be removed as the whole table is dropped in the beginning of the powerflow-part.

True, I deleted the respective lines.

**Pull request merged**
