### PR TITLE
Add dreaft of BPMN for cosmmoclmgrid

### LINKED ISSUE #333: there is no DP preprocessing BPMN documentation about cosmoclmgrid
Document where _climate.cosmoclmgrid_ comes from.

### PR DESCRIPTION
**Pull request by gplssm**
fix #333

### CODE REVIEW

**Comment by gplssm** [comment]
cosmoclmgrid must be created before supply data is imported and preprocessed. The script `ego_dp_supply_add_coastdat_gid.sql` updates power plant tables with location information from cosmoclmgrid.
Therefore, in the structure BPMN, cosmoclmgrid needs to be linked to supply preprocessing in #336.
In #335 don't forget to document `ego_dp_supply_add_coastdat_gid.sql`.

**Comment by gplssm** [comment]
@IlkaCu, I completed the documentation here. I did

- Adding the script `ego_dp_supply_add_coastdat_gid.sql`
- Made sure that cosmoclm part is linked to supply part in the overview graphic

Could you please review?

I assign myself which means for me that I'm responsible for merging, once the review is done.

**Comment by IlkaCu** [comment]
It seems that script `ego_dp_supply_add_coastdat_gid.sql` is redundant and no integral part of the preprocessing. 

1. it accesses the outdated table `coastdat.cosmoclmgrid`
2. column `coastdat_gid` is not (anymore) present in supply tables (e.g. `model_draft.ego_dp_supply_res_powerplant`), but replaced by `w_id`
3. w_id is assigned to supply tables in the dataprocessing itself  in `ego_dp_powerflow_assignment_otgid.sql` accessing table `coastdat.cosmoclmgrid`
4. Table `model_draft.ego_conv_powerplant_costdat_gid` is not accessed in the dataprocessing or other preprocessing parts

Therefore I suggest to remove this script and adjust the BPMN accordingly.

**Comment by IlkaCu** [comment]
It seems that script `ego_dp_supply_add_coastdat_gid.sql` is redundant and no integral part of the preprocessing. 

1. it accesses the outdated table `coastdat.cosmoclmgrid`
2. column `coastdat_gid` is not (anymore) present in supply tables (e.g. `model_draft.ego_dp_supply_res_powerplant`), but replaced by `w_id`
3. w_id is assigned to supply tables in the dataprocessing itself  in `ego_dp_powerflow_assignment_otgid.sql` accessing table `coastdat.cosmoclmgrid`
4. Table `model_draft.ego_conv_powerplant_costdat_gid` is not accessed in the dataprocessing or other preprocessing parts

Therefore I suggest to move this script to the utility folder (or remove it) and adjust the BPMN accordingly.

**Review by IlkaCu — APPROVED** [review]

**Review by ClaraBuettner — APPROVED** [review]

**Pull request merged**
