### PR TITLE
Refactor/dp repository structure

### PR DESCRIPTION
**Pull request by IlkaCu**
I implemented the new repository structure and already moved the files 'eGo_preprocessing.py' and ' 	ego_pre_slp_parameters.sql' into the new 'preprocessing' folder. I would leave it to the authors of the further preprocessing scripts to move them to their new location. 
The archive and all obsolete top level folders where moved to 'utilities'.
The preprocessing folder needs to be completed to create an executable preprocessing script.

### CODE REVIEW

**Comment by Ludee** [comment]
Another idea is to move the "functions" folder one level up from _dataprocessing\sql_snippets\functions_ to _dataprocessing\functions_!?

**Comment by IlkaCu** [comment]
I updated issue #15 and noted that we need to clear the utilities folder and delete all obsolete files there.

**Comment by IlkaCu** [comment]
@gplssm: Please review this pull request!

**Comment by gplssm** [comment]
I support the point of @lukasol: remove as much as possible! From the utilities folder we can delete the archive (git does the job for us). Even the remaining could be deleted from my point of view. If you still need them, please keep them there, but only that ones you really need.

**Comment by IlkaCu** [comment]
I deleted all obsolete files from the utilities folder, except for those in the subfolder 'calc_ego_substation'. These are scripts from the RLI. @gplssm, @Ludee: Can you please check and remove those scripts?

**Pull request merged**
