### PR TITLE
Features/wind onshore calculation

### PR DESCRIPTION
**Pull request by MarlonSchlemminger**

### CODE REVIEW

**Comment by IlkaCu** [comment]
@Wolf: Upload table app_renpassgis.renewable_energy_map_1, schema app_renpassgis needs to be renamed to model_draft, table renewable energy_map_1 needs to be renamed. Code needs to be adjusted accordingly.

**Comment by IlkaCu** [comment]
Wolf will work on the to-dos mentioned above and afterwards we will merge this branch into the dev.

**Comment by wolfbunke** [comment]
Table is renamed and uploaded to oedb by using this script: https://gist.github.com/wolfbunke/33e949c25d407610c088f998a008064e

**Comment by wolfbunke** [comment]
I checked the code there is only one line which calls app_renpassgis.renewable_energy_map_1 and its changed now. 

@MarlonSchlemminger which scripts needs to run of the preprocessing?

**Comment by MarlonSchlemminger** [comment]
1. ego_simple-feedin_per_scenario.sql
2. simple_feedin.py
This script is new: https://github.com/openego/data_processing/blob/dev/preprocessing/sql_snippets/ego_setup_renewable_feedin.sql
It adds comments on both tables created in simple_feedin.py and therefore needs to run after simple_feedin.

**Comment by wolfbunke** [comment]
Thx, the script is now locally running at my PC. I will upload the data tomorrow.

**Pull request merged**
