### PR TITLE
Feature/bpmn docu

### PR DESCRIPTION
**Pull request by IlkaCu**
BPMN documentation for dataprocessing

### CODE REVIEW

**Review by gplssm — CHANGES_REQUESTED** [review]
In general, it looks really good! Thanks for doing this!

I have a few comments/questions

- in ego_dp_bpmn_sections_input.graphml the section INPUT DATA CHECK is mentioned which I can't find
- What about licenses for created datasets/tables? For example in ego_dp_bpmn_section_substation.graphml newly created tables have no license information in the BPMN. Do we want to it? Actually, I though yes, but on the other hand, this information can be easily retrieved from table's metadata
- In ego_dp_bpmn_sections_postprocessing.graphml, a blue box indicates OSPD is an input to the script. But the actual table which goes in there isn't mentioned. Could you please add this?
- There is no BPMN for the versioning part. Should this be added?

**Comment by IlkaCu** [comment]
> In general, it looks really good! Thanks for doing this!
> 
> I have a few comments/questions
> 
>     * in ego_dp_bpmn_sections_input.graphml the section INPUT DATA CHECK is mentioned which I can't find
Section INPUT DATA CHECK is not yet included in the BPMN. I wonder if the script _ego_dp_structure_input_verification.sql_, which is the only one in this section, is up-to-date and still needed. @gplssm: Can you have a look? If yes, I can create a corresponding BPMN documentation. 
> 
>     * What about licenses for created datasets/tables? For example in ego_dp_bpmn_section_substation.graphml newly created tables have no license information in the BPMN. Do we want to it? Actually, I though yes, but on the other hand, this information can be easily retrieved from table's metadata
As it is a duplication to the metadata, I would not include the license information in the BPMN. 

> 
>     * In ego_dp_bpmn_sections_postprocessing.graphml, a blue box indicates OSPD is an input to the script. But the actual table which goes in there isn't mentioned. Could you please add this?
It's table _model_draft.opsd_hourly_timeseries_ and already included in the BPMN
> 
>     * There is no BPMN for the versioning part. Should this be added?
Yes, I will create the BPMN

**Comment by IlkaCu** [comment]
I added BPMNs for the sections versioning and input data check.
@gplssm: Do you have any further comments before merging this branch?

**Review by gplssm — APPROVED** [review]
Nope, nothing to add. You can merge

**Pull request merged**
