### PR TITLE
Add BPMN for zensus data import and preprocessing

### LINKED ISSUE #329: there is no DP preprocessing BPMN documentation about zensus
Create a BPMN for that

### PR DESCRIPTION
**Pull request by gplssm**
fix #329

### CODE REVIEW

**Review by IlkaCu — COMMENTED** [review]
The documentation seems to describe the script 'ego_pp-destatis_zensus_import.sql' correctly, but the input tables 'orig_destatis.zensus_population_per_ha' and orig_destatis.zensus_population_per_ha_grid' do not (anymore) exist in the database.

**Comment by gplssm** [comment]
Thanks for the hint!
Tables are initially uploaded into orig_destatis tables and the further processed and move elsewhere. I'll update the documentation when automized this section #339. It's quite likely this part will be replaced by some python :snake:

**Comment by gplssm** [comment]
One question come up during updating the BPMN. How to deal with tables that are temporarily used and droped after the end of the section? For example, for importing raw zensus data `tmp_destatis.zensus_2011_pop_per_ha` is created (plus 2 more tables) and 2 scripts later it's deleted again. By now, I didn't document/colorize the table differently

**Comment by IlkaCu** [comment]
As the tables name indicates its temporary use it should be okay to document it in the same way as the permanent tables.

**Review by IlkaCu — APPROVED** [review]

**Pull request merged**
